name: FastAPI CI/CD with Docker Compose

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: bestbest/be-orders:latest
  DEPLOY_SERVER: 119.59.99.92
  DEPLOY_USER: root
  DEPLOY_PASSWORD: ${{ secrets.SERVER_PASSWORD }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  DOCKER_USERNAME: bestbest

jobs:
  build_and_push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

    - name: Build Docker image
      run: docker build -t bestbest/be-orders:latest .

    - name: Push Docker image to Docker Hub
      run: docker push bestbest/be-orders:latest

  deploy:
        name: Deploy to Server
        runs-on: ubuntu-latest
        needs: build_and_push

        steps:
        - name: Install sshpass
          run: sudo apt-get update && sudo apt-get install -y sshpass

        - name: Deploy to Server
          run: |
            export SSHPASS=$DEPLOY_PASSWORD
            sshpass -e ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_SERVER '

              docker system prune -a

              docker pull bestbest/be-orders:latest

              # Navigate to project directory
              cd /home/be-orderhub

              # Stop and remove existing containers
              docker compose down

              # Start new containers
              docker compose up -d

              # Check if containers are running
              docker compose ps
            '



